# Site settings
title: Night Sky Gazers
email:
description: > "Stargazing and astrophotography sessions near mumbai"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown
